version = "0.1"
name = "VPN Client configuration panel"

[main]
name = "Auto-configuration"

    [main.service]
    name = "Service"

        [main.service.status]
        ask = "VPN Client is {status} (log are available in Service > ynh-vpnclient)"
        type = "display_text"
        helpLink = "/yunohost/admin/#/services/ynh-vpnclient"

        [main.service.service_enabled]
        ask = "VPN active"
        choices = ["on", "off"]
        default = "off"
        helpText = "If you select 'off' your VPN will not run even if you restart your server"
        source="settings"

    [main.cube]
    name = "Cube file"
        
        [main.cube.file]
        ask = "Load a cube File"
        type = "file"
        default = ""
        helpLink = "https://labriqueinter.net/dotcubefiles.html"
        helpText = "You can get a cube file from a VPN provider supporting this format (search FFDN Internet Service Providers)"

[manual]
name = "Manual configuration"
    [manual.vpn]
    name = "VPN"
        
        [manual.vpn.server_name]
        ask = "Server address"
        type = "string"
        default = ""
        helpText = "Prefer to put directly the IP address of your VPN server here instead of domain name"
        source="settings"
        
        [manual.vpn.server_port]
        ask = "Server Port"
        type = "integer"
        default = "443"
        source="settings"
        
        [manual.vpn.server_proto]
        ask = "Protocol"
        choices = ["udp", "tcp"]
        default = "udp"
        source="settings"
        
        [manual.vpn.server_ip6]
        ask = "Delegated prefix (IPv6)"
        type = "string"
        default = ""
        optional = true
        source="settings"

    [manual.auth]
    name = "Authentication"
        
        [manual.auth.server_ca]
        ask = "Update Server CA"
        type = "file"
        default = ""
        helpText = "You should upload a CA certificate to start"
        source="/etc/openvpn/keys/ca-server.crt"
        
        [manual.auth.crt]
        ask = "Update Client Certificate"
        type = "file"
        default = ""
        optional = true
        source="/etc/openvpn/keys/user.crt"
        
        [manual.auth.key]
        ask = "Update Client Key"
        type = "file"
        default = ""
        help = "This file begins with -----BEGIN PRIVATE KEY-----"
        optional = true
        source="/etc/openvpn/keys/user.key"
        
        [manual.auth.ta]
        ask = "Upload Shared-Secret"
        type = "file"
        default = ""
        optional = true
        source="/etc/openvpn/keys/user_ta.key"
        
        [manual.auth.login_user]
        ask = "Username"
        type = "string"
        default = ""
        optional = true
        source="settings"
        
        [manual.auth.login_passphrase]
        ask = "Password"
        type = "password"
        default = ""
        optional = true
        source="settings"

    [manual.dns]
    name = "DNS"

        [manual.dns.dns0]
        ask = "First resolver"
        type = "string"
        default = ""
        source="settings"

        [manual.dns.dns1]
        ask = "Second resolver"
        type = "string"
        default = ""
        source="settings"

[advanced]
name = "Advanced configuration"

    [advanced.ovpn]
    name = ""

        [advanced.ovpn.ovpn]
        ask = "OVPN template"
        type = "text"
        source="/etc/openvpn/client.conf.tpl"
